<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="XTI_Core.Fakes" Version="1.10.26-dev251122155254802" />
		<PackageReference Include="XTI_Core.Extensions" Version="1.10.26-dev251122155254802" />
		<PackageReference Include="XTI_HubAppClient.Extensions" Version="1.5.3" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="NUnit" Version="4.4.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.11.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="XTI_Secrets.Extensions" Version="1.8.14-dev251122160128621" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Internal\XTI_JobsDB.SqlServer\XTI_JobsDB.SqlServer.csproj" />
		<ProjectReference Include="..\..\Internal\XTI_ScheduledJobsWebAppApi\XTI_ScheduledJobsWebAppApi.csproj" />
		<ProjectReference Include="..\..\Lib\XTI_ScheduledJobsAppClient\XTI_ScheduledJobsAppClient.csproj" />
		<ProjectReference Include="..\XTI_ScheduledJobSharedTests\XTI_ScheduledJobSharedTests.csproj" />
	</ItemGroup>

</Project>
