<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="XTI_ApiClientGeneratorTask" Version="1.4.2-dev251122171943068" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\XTI_ScheduledJobsWebAppApiActions\XTI_ScheduledJobsWebAppApiActions.csproj" />
	</ItemGroup>

</Project>
